apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/divya96-sudo/argocd-front-backend-config.git
    targetRevision: HEAD
    path: frontend-config
  destination:
    server: https://kubernetes.default.svc
    namespace: app-ns
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/divya96-sudo/argocd-front-backend-config.git
    targetRevision: HEAD
    path: backend-config
  destination:
    server: https://kubernetes.default.svc
    namespace: app-ns
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true