apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/divya96-sudo/argocd-front-backend-config.git
    targetRevision: HEAD
    path: .
    #directory:
    #  recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ns
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true