apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-smoke-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    # argocd.argoproj.io/hook: Skip
spec:
  template:
    spec:
      containers:
      - name: smoke-test
        image: curlimages/curl:latest
        # command: ["curl", "-f", "http://frontend-service:80"]
        command: ["/bin/sh", "-c", "sleep 10 && echo 'Post-sync smoke test completed successfully'"]
      restartPolicy: Never